global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.62.40:8000']
        labels:
          job: 'prometheus'
          __path__: '/metrics'

